---
- hosts: servers
  tasks:
    - name: Create a group called jellyfin
      ansible.builtin.group: 
        name: jellyfin
        state: present
    
    - name: Create a user called jellyfin
      ansible.builtin.user:
        name: jellyfin
        groups: jellyfin
        comment: Jellyfin service account
        shell: /usr/sbin/nologin
        home: /nonexistent
        system: yes
        create_home: no
        state: present
    
    - name: Return user and group id via ansible
      command: id jellyfin
      register: out

    - debug: var=out.stdout_lines